### ISSUE TITLE
Can you reward mining based on total stake slots?

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-layer1-facade#16]
Our current preview 1 version issue mining reward to every miner evenly. Can we issue the reward based on how many slots the miner has? The more staking slots, the higher reward.  The reward is issued based on slots not the miner. For example, Alice has CML#1 with 5 slots, Bob has CML#2 with 3 slots, Charlie has CML#3 with 2 slots. If the total reward in this block is 10T. CML#1 receives 5, CML#2 receives 3T and CML#3 receives 2T. Then within the 5, 3 and 2, the distribution is based on the staking distribution algorithm.

**Comment by kevingzhang** [comment]
@raindust you can also get involved to this discussion

**Comment by liyangwood** [comment]
@raindust please take over.

**Comment by raindust** [comment]
Add task point parameters in https://github.com/tearust/tea-camellia/commit/a82834afddc9f2f7790cdfde18698565fccb7854, will be updated in next version (fast-0.1.7)
